// <auto-generated />
using System;
using LPH.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LPH.Infrastructure.Migrations
{
    [DbContext(typeof(LPHDBContext))]
    [Migration("20210519181846_InitialCatalog")]
    partial class InitialCatalog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("LPH.Core.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Extencion")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<int>("IdOrden")
                        .HasColumnType("integer");

                    b.Property<long>("SizeFile")
                        .HasColumnType("bigint");

                    b.Property<string>("UriString")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("IdOrden");

                    b.ToTable("files");
                });

            modelBuilder.Entity("LPH.Core.Entities.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Alto")
                        .HasColumnType("double precision");

                    b.Property<double>("Ancho")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("FechaRealizacionDeseada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.Property<string>("Localizacion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MaterialBarda")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Organizacion")
                        .HasColumnType("integer");

                    b.Property<string>("Tematica")
                        .HasMaxLength(516)
                        .HasColumnType("character varying(516)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.ToTable("ordenes");
                });

            modelBuilder.Entity("LPH.Core.Entities.OrdenComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("Calificacion")
                        .HasMaxLength(5)
                        .HasColumnType("real");

                    b.Property<string>("Comentario")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("IdOrden")
                        .HasColumnType("integer");

                    b.Property<int>("IdUser")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IdOrden");

                    b.HasIndex("IdUser");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("LPH.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GoogleUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<bool>("Suscrito")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("LPH.Core.Entities.File", b =>
                {
                    b.HasOne("LPH.Core.Entities.Orden", "IdOrdenNavigation")
                        .WithMany("Files")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdOrdenNavigation");
                });

            modelBuilder.Entity("LPH.Core.Entities.Orden", b =>
                {
                    b.HasOne("LPH.Core.Entities.Usuario", "IdUserNavigation")
                        .WithMany("Ordenes")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("LPH.Core.Entities.OrdenComment", b =>
                {
                    b.HasOne("LPH.Core.Entities.Orden", "IdOrdenNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdOrden")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LPH.Core.Entities.Usuario", "IdUserNavigation")
                        .WithMany("Comments")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdOrdenNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("LPH.Core.Entities.Orden", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("LPH.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
